/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-01 at 01:18:52 UTC 
 * Modify at your own risk.
 */

package com.appspot.ba_info.bibliotecas;

/**
 * Service definition for Bibliotecas (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link BibliotecasRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Bibliotecas extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the bibliotecas library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://ba-info.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "bibliotecas/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Bibliotecas(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Bibliotecas(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the BibliotecaEndpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Bibliotecas bibliotecas = new Bibliotecas(...);}
   *   {@code Bibliotecas.BibliotecaEndpoint.List request = bibliotecas.bibliotecaEndpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public BibliotecaEndpoint bibliotecaEndpoint() {
    return new BibliotecaEndpoint();
  }

  /**
   * The "bibliotecaEndpoint" collection of methods.
   */
  public class BibliotecaEndpoint {

    /**
     * Create a request for the method "bibliotecaEndpoint.getBiblioteca".
     *
     * This request holds the parameters needed by the the bibliotecas server.  After setting any
     * optional parameters, call the {@link GetBiblioteca#execute()} method to invoke the remote
     * operation.
     *
     * @param id
     * @return the request
     */
    public GetBiblioteca getBiblioteca(java.lang.Long id) throws java.io.IOException {
      GetBiblioteca result = new GetBiblioteca(id);
      initialize(result);
      return result;
    }

    public class GetBiblioteca extends BibliotecasRequest<com.appspot.ba_info.bibliotecas.model.Biblioteca> {

      private static final String REST_PATH = "biblioteca/{id}";

      /**
       * Create a request for the method "bibliotecaEndpoint.getBiblioteca".
       *
       * This request holds the parameters needed by the the bibliotecas server.  After setting any
       * optional parameters, call the {@link GetBiblioteca#execute()} method to invoke the remote
       * operation. <p> {@link GetBiblioteca#initialize(com.google.api.client.googleapis.services.Abstra
       * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected GetBiblioteca(java.lang.Long id) {
        super(Bibliotecas.this, "GET", REST_PATH, null, com.appspot.ba_info.bibliotecas.model.Biblioteca.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetBiblioteca setAlt(java.lang.String alt) {
        return (GetBiblioteca) super.setAlt(alt);
      }

      @Override
      public GetBiblioteca setFields(java.lang.String fields) {
        return (GetBiblioteca) super.setFields(fields);
      }

      @Override
      public GetBiblioteca setKey(java.lang.String key) {
        return (GetBiblioteca) super.setKey(key);
      }

      @Override
      public GetBiblioteca setOauthToken(java.lang.String oauthToken) {
        return (GetBiblioteca) super.setOauthToken(oauthToken);
      }

      @Override
      public GetBiblioteca setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetBiblioteca) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetBiblioteca setQuotaUser(java.lang.String quotaUser) {
        return (GetBiblioteca) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetBiblioteca setUserIp(java.lang.String userIp) {
        return (GetBiblioteca) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public GetBiblioteca setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public GetBiblioteca set(String parameterName, Object value) {
        return (GetBiblioteca) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "bibliotecaEndpoint.insertBiblioteca".
     *
     * This request holds the parameters needed by the the bibliotecas server.  After setting any
     * optional parameters, call the {@link InsertBiblioteca#execute()} method to invoke the remote
     * operation.
     *
     * @param content the {@link com.appspot.ba_info.bibliotecas.model.Biblioteca}
     * @return the request
     */
    public InsertBiblioteca insertBiblioteca(com.appspot.ba_info.bibliotecas.model.Biblioteca content) throws java.io.IOException {
      InsertBiblioteca result = new InsertBiblioteca(content);
      initialize(result);
      return result;
    }

    public class InsertBiblioteca extends BibliotecasRequest<com.appspot.ba_info.bibliotecas.model.Biblioteca> {

      private static final String REST_PATH = "biblioteca";

      /**
       * Create a request for the method "bibliotecaEndpoint.insertBiblioteca".
       *
       * This request holds the parameters needed by the the bibliotecas server.  After setting any
       * optional parameters, call the {@link InsertBiblioteca#execute()} method to invoke the remote
       * operation. <p> {@link InsertBiblioteca#initialize(com.google.api.client.googleapis.services.Abs
       * tractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.ba_info.bibliotecas.model.Biblioteca}
       * @since 1.13
       */
      protected InsertBiblioteca(com.appspot.ba_info.bibliotecas.model.Biblioteca content) {
        super(Bibliotecas.this, "POST", REST_PATH, content, com.appspot.ba_info.bibliotecas.model.Biblioteca.class);
      }

      @Override
      public InsertBiblioteca setAlt(java.lang.String alt) {
        return (InsertBiblioteca) super.setAlt(alt);
      }

      @Override
      public InsertBiblioteca setFields(java.lang.String fields) {
        return (InsertBiblioteca) super.setFields(fields);
      }

      @Override
      public InsertBiblioteca setKey(java.lang.String key) {
        return (InsertBiblioteca) super.setKey(key);
      }

      @Override
      public InsertBiblioteca setOauthToken(java.lang.String oauthToken) {
        return (InsertBiblioteca) super.setOauthToken(oauthToken);
      }

      @Override
      public InsertBiblioteca setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (InsertBiblioteca) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public InsertBiblioteca setQuotaUser(java.lang.String quotaUser) {
        return (InsertBiblioteca) super.setQuotaUser(quotaUser);
      }

      @Override
      public InsertBiblioteca setUserIp(java.lang.String userIp) {
        return (InsertBiblioteca) super.setUserIp(userIp);
      }

      @Override
      public InsertBiblioteca set(String parameterName, Object value) {
        return (InsertBiblioteca) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "bibliotecaEndpoint.listBiblioteca".
     *
     * This request holds the parameters needed by the the bibliotecas server.  After setting any
     * optional parameters, call the {@link ListBiblioteca#execute()} method to invoke the remote
     * operation.
     *
     * @return the request
     */
    public ListBiblioteca listBiblioteca() throws java.io.IOException {
      ListBiblioteca result = new ListBiblioteca();
      initialize(result);
      return result;
    }

    public class ListBiblioteca extends BibliotecasRequest<com.appspot.ba_info.bibliotecas.model.BibliotecaCollection> {

      private static final String REST_PATH = "biblioteca";

      /**
       * Create a request for the method "bibliotecaEndpoint.listBiblioteca".
       *
       * This request holds the parameters needed by the the bibliotecas server.  After setting any
       * optional parameters, call the {@link ListBiblioteca#execute()} method to invoke the remote
       * operation. <p> {@link ListBiblioteca#initialize(com.google.api.client.googleapis.services.Abstr
       * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @since 1.13
       */
      protected ListBiblioteca() {
        super(Bibliotecas.this, "GET", REST_PATH, null, com.appspot.ba_info.bibliotecas.model.BibliotecaCollection.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public ListBiblioteca setAlt(java.lang.String alt) {
        return (ListBiblioteca) super.setAlt(alt);
      }

      @Override
      public ListBiblioteca setFields(java.lang.String fields) {
        return (ListBiblioteca) super.setFields(fields);
      }

      @Override
      public ListBiblioteca setKey(java.lang.String key) {
        return (ListBiblioteca) super.setKey(key);
      }

      @Override
      public ListBiblioteca setOauthToken(java.lang.String oauthToken) {
        return (ListBiblioteca) super.setOauthToken(oauthToken);
      }

      @Override
      public ListBiblioteca setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (ListBiblioteca) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public ListBiblioteca setQuotaUser(java.lang.String quotaUser) {
        return (ListBiblioteca) super.setQuotaUser(quotaUser);
      }

      @Override
      public ListBiblioteca setUserIp(java.lang.String userIp) {
        return (ListBiblioteca) super.setUserIp(userIp);
      }

      @Override
      public ListBiblioteca set(String parameterName, Object value) {
        return (ListBiblioteca) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "bibliotecaEndpoint.removeBiblioteca".
     *
     * This request holds the parameters needed by the the bibliotecas server.  After setting any
     * optional parameters, call the {@link RemoveBiblioteca#execute()} method to invoke the remote
     * operation.
     *
     * @param id
     * @return the request
     */
    public RemoveBiblioteca removeBiblioteca(java.lang.Long id) throws java.io.IOException {
      RemoveBiblioteca result = new RemoveBiblioteca(id);
      initialize(result);
      return result;
    }

    public class RemoveBiblioteca extends BibliotecasRequest<com.appspot.ba_info.bibliotecas.model.Biblioteca> {

      private static final String REST_PATH = "biblioteca/{id}";

      /**
       * Create a request for the method "bibliotecaEndpoint.removeBiblioteca".
       *
       * This request holds the parameters needed by the the bibliotecas server.  After setting any
       * optional parameters, call the {@link RemoveBiblioteca#execute()} method to invoke the remote
       * operation. <p> {@link RemoveBiblioteca#initialize(com.google.api.client.googleapis.services.Abs
       * tractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected RemoveBiblioteca(java.lang.Long id) {
        super(Bibliotecas.this, "DELETE", REST_PATH, null, com.appspot.ba_info.bibliotecas.model.Biblioteca.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public RemoveBiblioteca setAlt(java.lang.String alt) {
        return (RemoveBiblioteca) super.setAlt(alt);
      }

      @Override
      public RemoveBiblioteca setFields(java.lang.String fields) {
        return (RemoveBiblioteca) super.setFields(fields);
      }

      @Override
      public RemoveBiblioteca setKey(java.lang.String key) {
        return (RemoveBiblioteca) super.setKey(key);
      }

      @Override
      public RemoveBiblioteca setOauthToken(java.lang.String oauthToken) {
        return (RemoveBiblioteca) super.setOauthToken(oauthToken);
      }

      @Override
      public RemoveBiblioteca setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (RemoveBiblioteca) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public RemoveBiblioteca setQuotaUser(java.lang.String quotaUser) {
        return (RemoveBiblioteca) super.setQuotaUser(quotaUser);
      }

      @Override
      public RemoveBiblioteca setUserIp(java.lang.String userIp) {
        return (RemoveBiblioteca) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public RemoveBiblioteca setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public RemoveBiblioteca set(String parameterName, Object value) {
        return (RemoveBiblioteca) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "bibliotecaEndpoint.updateBiblioteca".
     *
     * This request holds the parameters needed by the the bibliotecas server.  After setting any
     * optional parameters, call the {@link UpdateBiblioteca#execute()} method to invoke the remote
     * operation.
     *
     * @param content the {@link com.appspot.ba_info.bibliotecas.model.Biblioteca}
     * @return the request
     */
    public UpdateBiblioteca updateBiblioteca(com.appspot.ba_info.bibliotecas.model.Biblioteca content) throws java.io.IOException {
      UpdateBiblioteca result = new UpdateBiblioteca(content);
      initialize(result);
      return result;
    }

    public class UpdateBiblioteca extends BibliotecasRequest<com.appspot.ba_info.bibliotecas.model.Biblioteca> {

      private static final String REST_PATH = "biblioteca";

      /**
       * Create a request for the method "bibliotecaEndpoint.updateBiblioteca".
       *
       * This request holds the parameters needed by the the bibliotecas server.  After setting any
       * optional parameters, call the {@link UpdateBiblioteca#execute()} method to invoke the remote
       * operation. <p> {@link UpdateBiblioteca#initialize(com.google.api.client.googleapis.services.Abs
       * tractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.ba_info.bibliotecas.model.Biblioteca}
       * @since 1.13
       */
      protected UpdateBiblioteca(com.appspot.ba_info.bibliotecas.model.Biblioteca content) {
        super(Bibliotecas.this, "PUT", REST_PATH, content, com.appspot.ba_info.bibliotecas.model.Biblioteca.class);
      }

      @Override
      public UpdateBiblioteca setAlt(java.lang.String alt) {
        return (UpdateBiblioteca) super.setAlt(alt);
      }

      @Override
      public UpdateBiblioteca setFields(java.lang.String fields) {
        return (UpdateBiblioteca) super.setFields(fields);
      }

      @Override
      public UpdateBiblioteca setKey(java.lang.String key) {
        return (UpdateBiblioteca) super.setKey(key);
      }

      @Override
      public UpdateBiblioteca setOauthToken(java.lang.String oauthToken) {
        return (UpdateBiblioteca) super.setOauthToken(oauthToken);
      }

      @Override
      public UpdateBiblioteca setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (UpdateBiblioteca) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public UpdateBiblioteca setQuotaUser(java.lang.String quotaUser) {
        return (UpdateBiblioteca) super.setQuotaUser(quotaUser);
      }

      @Override
      public UpdateBiblioteca setUserIp(java.lang.String userIp) {
        return (UpdateBiblioteca) super.setUserIp(userIp);
      }

      @Override
      public UpdateBiblioteca set(String parameterName, Object value) {
        return (UpdateBiblioteca) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Bibliotecas}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Bibliotecas}. */
    @Override
    public Bibliotecas build() {
      return new Bibliotecas(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link BibliotecasRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setBibliotecasRequestInitializer(
        BibliotecasRequestInitializer bibliotecasRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(bibliotecasRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
