/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-01 at 01:15:34 UTC 
 * Modify at your own risk.
 */

package com.appspot.ba_info.hospitales.model;

/**
 * Model definition for Hospital.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the hospitales. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Hospital extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String altura;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String calle;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String codPostal;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String dependAdm;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String direccion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fax;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String guardia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer idHospital;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float latitud;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float longitud;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String modoAt1;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String modoAt2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombre;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String separatorChar;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sourceURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String telefono;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tipo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tipoEspecialidad;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String web;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAltura() {
    return altura;
  }

  /**
   * @param altura altura or {@code null} for none
   */
  public Hospital setAltura(java.lang.String altura) {
    this.altura = altura;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCalle() {
    return calle;
  }

  /**
   * @param calle calle or {@code null} for none
   */
  public Hospital setCalle(java.lang.String calle) {
    this.calle = calle;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCodPostal() {
    return codPostal;
  }

  /**
   * @param codPostal codPostal or {@code null} for none
   */
  public Hospital setCodPostal(java.lang.String codPostal) {
    this.codPostal = codPostal;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDependAdm() {
    return dependAdm;
  }

  /**
   * @param dependAdm dependAdm or {@code null} for none
   */
  public Hospital setDependAdm(java.lang.String dependAdm) {
    this.dependAdm = dependAdm;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDireccion() {
    return direccion;
  }

  /**
   * @param direccion direccion or {@code null} for none
   */
  public Hospital setDireccion(java.lang.String direccion) {
    this.direccion = direccion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFax() {
    return fax;
  }

  /**
   * @param fax fax or {@code null} for none
   */
  public Hospital setFax(java.lang.String fax) {
    this.fax = fax;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGuardia() {
    return guardia;
  }

  /**
   * @param guardia guardia or {@code null} for none
   */
  public Hospital setGuardia(java.lang.String guardia) {
    this.guardia = guardia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Hospital setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getIdHospital() {
    return idHospital;
  }

  /**
   * @param idHospital idHospital or {@code null} for none
   */
  public Hospital setIdHospital(java.lang.Integer idHospital) {
    this.idHospital = idHospital;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getLatitud() {
    return latitud;
  }

  /**
   * @param latitud latitud or {@code null} for none
   */
  public Hospital setLatitud(java.lang.Float latitud) {
    this.latitud = latitud;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getLongitud() {
    return longitud;
  }

  /**
   * @param longitud longitud or {@code null} for none
   */
  public Hospital setLongitud(java.lang.Float longitud) {
    this.longitud = longitud;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getModoAt1() {
    return modoAt1;
  }

  /**
   * @param modoAt1 modoAt1 or {@code null} for none
   */
  public Hospital setModoAt1(java.lang.String modoAt1) {
    this.modoAt1 = modoAt1;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getModoAt2() {
    return modoAt2;
  }

  /**
   * @param modoAt2 modoAt2 or {@code null} for none
   */
  public Hospital setModoAt2(java.lang.String modoAt2) {
    this.modoAt2 = modoAt2;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombre() {
    return nombre;
  }

  /**
   * @param nombre nombre or {@code null} for none
   */
  public Hospital setNombre(java.lang.String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSeparatorChar() {
    return separatorChar;
  }

  /**
   * @param separatorChar separatorChar or {@code null} for none
   */
  public Hospital setSeparatorChar(java.lang.String separatorChar) {
    this.separatorChar = separatorChar;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSourceURL() {
    return sourceURL;
  }

  /**
   * @param sourceURL sourceURL or {@code null} for none
   */
  public Hospital setSourceURL(java.lang.String sourceURL) {
    this.sourceURL = sourceURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTelefono() {
    return telefono;
  }

  /**
   * @param telefono telefono or {@code null} for none
   */
  public Hospital setTelefono(java.lang.String telefono) {
    this.telefono = telefono;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTipo() {
    return tipo;
  }

  /**
   * @param tipo tipo or {@code null} for none
   */
  public Hospital setTipo(java.lang.String tipo) {
    this.tipo = tipo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTipoEspecialidad() {
    return tipoEspecialidad;
  }

  /**
   * @param tipoEspecialidad tipoEspecialidad or {@code null} for none
   */
  public Hospital setTipoEspecialidad(java.lang.String tipoEspecialidad) {
    this.tipoEspecialidad = tipoEspecialidad;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWeb() {
    return web;
  }

  /**
   * @param web web or {@code null} for none
   */
  public Hospital setWeb(java.lang.String web) {
    this.web = web;
    return this;
  }

  @Override
  public Hospital set(String fieldName, Object value) {
    return (Hospital) super.set(fieldName, value);
  }

  @Override
  public Hospital clone() {
    return (Hospital) super.clone();
  }

}
