/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-01 at 01:18:52 UTC 
 * Modify at your own risk.
 */

package com.appspot.ba_info.bibliotecas.model;

/**
 * Model definition for Biblioteca.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the bibliotecas. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Biblioteca extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String barrios;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String comuna;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String domicilio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer idBiblioteca;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float latitud;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float longitud;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombre;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String numeroMapa;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String separatorChar;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sourceURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String telefono;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tipo;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBarrios() {
    return barrios;
  }

  /**
   * @param barrios barrios or {@code null} for none
   */
  public Biblioteca setBarrios(java.lang.String barrios) {
    this.barrios = barrios;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getComuna() {
    return comuna;
  }

  /**
   * @param comuna comuna or {@code null} for none
   */
  public Biblioteca setComuna(java.lang.String comuna) {
    this.comuna = comuna;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDomicilio() {
    return domicilio;
  }

  /**
   * @param domicilio domicilio or {@code null} for none
   */
  public Biblioteca setDomicilio(java.lang.String domicilio) {
    this.domicilio = domicilio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public Biblioteca setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Biblioteca setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getIdBiblioteca() {
    return idBiblioteca;
  }

  /**
   * @param idBiblioteca idBiblioteca or {@code null} for none
   */
  public Biblioteca setIdBiblioteca(java.lang.Integer idBiblioteca) {
    this.idBiblioteca = idBiblioteca;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getLatitud() {
    return latitud;
  }

  /**
   * @param latitud latitud or {@code null} for none
   */
  public Biblioteca setLatitud(java.lang.Float latitud) {
    this.latitud = latitud;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getLongitud() {
    return longitud;
  }

  /**
   * @param longitud longitud or {@code null} for none
   */
  public Biblioteca setLongitud(java.lang.Float longitud) {
    this.longitud = longitud;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombre() {
    return nombre;
  }

  /**
   * @param nombre nombre or {@code null} for none
   */
  public Biblioteca setNombre(java.lang.String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNumeroMapa() {
    return numeroMapa;
  }

  /**
   * @param numeroMapa numeroMapa or {@code null} for none
   */
  public Biblioteca setNumeroMapa(java.lang.String numeroMapa) {
    this.numeroMapa = numeroMapa;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSeparatorChar() {
    return separatorChar;
  }

  /**
   * @param separatorChar separatorChar or {@code null} for none
   */
  public Biblioteca setSeparatorChar(java.lang.String separatorChar) {
    this.separatorChar = separatorChar;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSourceURL() {
    return sourceURL;
  }

  /**
   * @param sourceURL sourceURL or {@code null} for none
   */
  public Biblioteca setSourceURL(java.lang.String sourceURL) {
    this.sourceURL = sourceURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTelefono() {
    return telefono;
  }

  /**
   * @param telefono telefono or {@code null} for none
   */
  public Biblioteca setTelefono(java.lang.String telefono) {
    this.telefono = telefono;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTipo() {
    return tipo;
  }

  /**
   * @param tipo tipo or {@code null} for none
   */
  public Biblioteca setTipo(java.lang.String tipo) {
    this.tipo = tipo;
    return this;
  }

  @Override
  public Biblioteca set(String fieldName, Object value) {
    return (Biblioteca) super.set(fieldName, value);
  }

  @Override
  public Biblioteca clone() {
    return (Biblioteca) super.clone();
  }

}
