/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-01 at 01:19:31 UTC 
 * Modify at your own risk.
 */

package com.appspot.ba_info.bicicleterias.model;

/**
 * Model definition for Bicicleteria.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the bicicleterias. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Bicicleteria extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String barrio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String comuna;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String domicilio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float latitud;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float longitud;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombre;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String separatorChar;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sourceURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String telefono;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String web;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBarrio() {
    return barrio;
  }

  /**
   * @param barrio barrio or {@code null} for none
   */
  public Bicicleteria setBarrio(java.lang.String barrio) {
    this.barrio = barrio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getComuna() {
    return comuna;
  }

  /**
   * @param comuna comuna or {@code null} for none
   */
  public Bicicleteria setComuna(java.lang.String comuna) {
    this.comuna = comuna;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDomicilio() {
    return domicilio;
  }

  /**
   * @param domicilio domicilio or {@code null} for none
   */
  public Bicicleteria setDomicilio(java.lang.String domicilio) {
    this.domicilio = domicilio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Bicicleteria setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getLatitud() {
    return latitud;
  }

  /**
   * @param latitud latitud or {@code null} for none
   */
  public Bicicleteria setLatitud(java.lang.Float latitud) {
    this.latitud = latitud;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getLongitud() {
    return longitud;
  }

  /**
   * @param longitud longitud or {@code null} for none
   */
  public Bicicleteria setLongitud(java.lang.Float longitud) {
    this.longitud = longitud;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombre() {
    return nombre;
  }

  /**
   * @param nombre nombre or {@code null} for none
   */
  public Bicicleteria setNombre(java.lang.String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSeparatorChar() {
    return separatorChar;
  }

  /**
   * @param separatorChar separatorChar or {@code null} for none
   */
  public Bicicleteria setSeparatorChar(java.lang.String separatorChar) {
    this.separatorChar = separatorChar;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSourceURL() {
    return sourceURL;
  }

  /**
   * @param sourceURL sourceURL or {@code null} for none
   */
  public Bicicleteria setSourceURL(java.lang.String sourceURL) {
    this.sourceURL = sourceURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTelefono() {
    return telefono;
  }

  /**
   * @param telefono telefono or {@code null} for none
   */
  public Bicicleteria setTelefono(java.lang.String telefono) {
    this.telefono = telefono;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWeb() {
    return web;
  }

  /**
   * @param web web or {@code null} for none
   */
  public Bicicleteria setWeb(java.lang.String web) {
    this.web = web;
    return this;
  }

  @Override
  public Bicicleteria set(String fieldName, Object value) {
    return (Bicicleteria) super.set(fieldName, value);
  }

  @Override
  public Bicicleteria clone() {
    return (Bicicleteria) super.clone();
  }

}
