/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-01 at 01:17:57 UTC 
 * Modify at your own risk.
 */

package com.appspot.ba_info.alojamientostursiticos;

/**
 * Service definition for Alojamientostursiticos (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AlojamientostursiticosRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Alojamientostursiticos extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the alojamientostursiticos library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://ba-info.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "alojamientostursiticos/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Alojamientostursiticos(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Alojamientostursiticos(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the AlojamientoTursiticoEndpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Alojamientostursiticos alojamientostursiticos = new Alojamientostursiticos(...);}
   *   {@code Alojamientostursiticos.AlojamientoTursiticoEndpoint.List request = alojamientostursiticos.alojamientoTursiticoEndpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public AlojamientoTursiticoEndpoint alojamientoTursiticoEndpoint() {
    return new AlojamientoTursiticoEndpoint();
  }

  /**
   * The "alojamientoTursiticoEndpoint" collection of methods.
   */
  public class AlojamientoTursiticoEndpoint {

    /**
     * Create a request for the method "alojamientoTursiticoEndpoint.getAlojamientoTursitico".
     *
     * This request holds the parameters needed by the the alojamientostursiticos server.  After setting
     * any optional parameters, call the {@link GetAlojamientoTursitico#execute()} method to invoke the
     * remote operation.
     *
     * @param id
     * @return the request
     */
    public GetAlojamientoTursitico getAlojamientoTursitico(java.lang.Long id) throws java.io.IOException {
      GetAlojamientoTursitico result = new GetAlojamientoTursitico(id);
      initialize(result);
      return result;
    }

    public class GetAlojamientoTursitico extends AlojamientostursiticosRequest<com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico> {

      private static final String REST_PATH = "alojamientotursitico/{id}";

      /**
       * Create a request for the method "alojamientoTursiticoEndpoint.getAlojamientoTursitico".
       *
       * This request holds the parameters needed by the the alojamientostursiticos server.  After
       * setting any optional parameters, call the {@link GetAlojamientoTursitico#execute()} method to
       * invoke the remote operation. <p> {@link GetAlojamientoTursitico#initialize(com.google.api.clien
       * t.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
       * immediately after invoking the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected GetAlojamientoTursitico(java.lang.Long id) {
        super(Alojamientostursiticos.this, "GET", REST_PATH, null, com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetAlojamientoTursitico setAlt(java.lang.String alt) {
        return (GetAlojamientoTursitico) super.setAlt(alt);
      }

      @Override
      public GetAlojamientoTursitico setFields(java.lang.String fields) {
        return (GetAlojamientoTursitico) super.setFields(fields);
      }

      @Override
      public GetAlojamientoTursitico setKey(java.lang.String key) {
        return (GetAlojamientoTursitico) super.setKey(key);
      }

      @Override
      public GetAlojamientoTursitico setOauthToken(java.lang.String oauthToken) {
        return (GetAlojamientoTursitico) super.setOauthToken(oauthToken);
      }

      @Override
      public GetAlojamientoTursitico setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetAlojamientoTursitico) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetAlojamientoTursitico setQuotaUser(java.lang.String quotaUser) {
        return (GetAlojamientoTursitico) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetAlojamientoTursitico setUserIp(java.lang.String userIp) {
        return (GetAlojamientoTursitico) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public GetAlojamientoTursitico setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public GetAlojamientoTursitico set(String parameterName, Object value) {
        return (GetAlojamientoTursitico) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "alojamientoTursiticoEndpoint.insertAlojamientoTursitico".
     *
     * This request holds the parameters needed by the the alojamientostursiticos server.  After setting
     * any optional parameters, call the {@link InsertAlojamientoTursitico#execute()} method to invoke
     * the remote operation.
     *
     * @param content the {@link com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico}
     * @return the request
     */
    public InsertAlojamientoTursitico insertAlojamientoTursitico(com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico content) throws java.io.IOException {
      InsertAlojamientoTursitico result = new InsertAlojamientoTursitico(content);
      initialize(result);
      return result;
    }

    public class InsertAlojamientoTursitico extends AlojamientostursiticosRequest<com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico> {

      private static final String REST_PATH = "alojamientotursitico";

      /**
       * Create a request for the method "alojamientoTursiticoEndpoint.insertAlojamientoTursitico".
       *
       * This request holds the parameters needed by the the alojamientostursiticos server.  After
       * setting any optional parameters, call the {@link InsertAlojamientoTursitico#execute()} method
       * to invoke the remote operation. <p> {@link InsertAlojamientoTursitico#initialize(com.google.api
       * .client.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this
       * instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico}
       * @since 1.13
       */
      protected InsertAlojamientoTursitico(com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico content) {
        super(Alojamientostursiticos.this, "POST", REST_PATH, content, com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico.class);
      }

      @Override
      public InsertAlojamientoTursitico setAlt(java.lang.String alt) {
        return (InsertAlojamientoTursitico) super.setAlt(alt);
      }

      @Override
      public InsertAlojamientoTursitico setFields(java.lang.String fields) {
        return (InsertAlojamientoTursitico) super.setFields(fields);
      }

      @Override
      public InsertAlojamientoTursitico setKey(java.lang.String key) {
        return (InsertAlojamientoTursitico) super.setKey(key);
      }

      @Override
      public InsertAlojamientoTursitico setOauthToken(java.lang.String oauthToken) {
        return (InsertAlojamientoTursitico) super.setOauthToken(oauthToken);
      }

      @Override
      public InsertAlojamientoTursitico setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (InsertAlojamientoTursitico) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public InsertAlojamientoTursitico setQuotaUser(java.lang.String quotaUser) {
        return (InsertAlojamientoTursitico) super.setQuotaUser(quotaUser);
      }

      @Override
      public InsertAlojamientoTursitico setUserIp(java.lang.String userIp) {
        return (InsertAlojamientoTursitico) super.setUserIp(userIp);
      }

      @Override
      public InsertAlojamientoTursitico set(String parameterName, Object value) {
        return (InsertAlojamientoTursitico) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "alojamientoTursiticoEndpoint.listAlojamientoTursitico".
     *
     * This request holds the parameters needed by the the alojamientostursiticos server.  After setting
     * any optional parameters, call the {@link ListAlojamientoTursitico#execute()} method to invoke the
     * remote operation.
     *
     * @return the request
     */
    public ListAlojamientoTursitico listAlojamientoTursitico() throws java.io.IOException {
      ListAlojamientoTursitico result = new ListAlojamientoTursitico();
      initialize(result);
      return result;
    }

    public class ListAlojamientoTursitico extends AlojamientostursiticosRequest<com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursiticoCollection> {

      private static final String REST_PATH = "alojamientotursitico";

      /**
       * Create a request for the method "alojamientoTursiticoEndpoint.listAlojamientoTursitico".
       *
       * This request holds the parameters needed by the the alojamientostursiticos server.  After
       * setting any optional parameters, call the {@link ListAlojamientoTursitico#execute()} method to
       * invoke the remote operation. <p> {@link ListAlojamientoTursitico#initialize(com.google.api.clie
       * nt.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
       * immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected ListAlojamientoTursitico() {
        super(Alojamientostursiticos.this, "GET", REST_PATH, null, com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursiticoCollection.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public ListAlojamientoTursitico setAlt(java.lang.String alt) {
        return (ListAlojamientoTursitico) super.setAlt(alt);
      }

      @Override
      public ListAlojamientoTursitico setFields(java.lang.String fields) {
        return (ListAlojamientoTursitico) super.setFields(fields);
      }

      @Override
      public ListAlojamientoTursitico setKey(java.lang.String key) {
        return (ListAlojamientoTursitico) super.setKey(key);
      }

      @Override
      public ListAlojamientoTursitico setOauthToken(java.lang.String oauthToken) {
        return (ListAlojamientoTursitico) super.setOauthToken(oauthToken);
      }

      @Override
      public ListAlojamientoTursitico setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (ListAlojamientoTursitico) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public ListAlojamientoTursitico setQuotaUser(java.lang.String quotaUser) {
        return (ListAlojamientoTursitico) super.setQuotaUser(quotaUser);
      }

      @Override
      public ListAlojamientoTursitico setUserIp(java.lang.String userIp) {
        return (ListAlojamientoTursitico) super.setUserIp(userIp);
      }

      @Override
      public ListAlojamientoTursitico set(String parameterName, Object value) {
        return (ListAlojamientoTursitico) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "alojamientoTursiticoEndpoint.removeAlojamientoTursitico".
     *
     * This request holds the parameters needed by the the alojamientostursiticos server.  After setting
     * any optional parameters, call the {@link RemoveAlojamientoTursitico#execute()} method to invoke
     * the remote operation.
     *
     * @param id
     * @return the request
     */
    public RemoveAlojamientoTursitico removeAlojamientoTursitico(java.lang.Long id) throws java.io.IOException {
      RemoveAlojamientoTursitico result = new RemoveAlojamientoTursitico(id);
      initialize(result);
      return result;
    }

    public class RemoveAlojamientoTursitico extends AlojamientostursiticosRequest<com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico> {

      private static final String REST_PATH = "alojamientotursitico/{id}";

      /**
       * Create a request for the method "alojamientoTursiticoEndpoint.removeAlojamientoTursitico".
       *
       * This request holds the parameters needed by the the alojamientostursiticos server.  After
       * setting any optional parameters, call the {@link RemoveAlojamientoTursitico#execute()} method
       * to invoke the remote operation. <p> {@link RemoveAlojamientoTursitico#initialize(com.google.api
       * .client.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this
       * instance immediately after invoking the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected RemoveAlojamientoTursitico(java.lang.Long id) {
        super(Alojamientostursiticos.this, "DELETE", REST_PATH, null, com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public RemoveAlojamientoTursitico setAlt(java.lang.String alt) {
        return (RemoveAlojamientoTursitico) super.setAlt(alt);
      }

      @Override
      public RemoveAlojamientoTursitico setFields(java.lang.String fields) {
        return (RemoveAlojamientoTursitico) super.setFields(fields);
      }

      @Override
      public RemoveAlojamientoTursitico setKey(java.lang.String key) {
        return (RemoveAlojamientoTursitico) super.setKey(key);
      }

      @Override
      public RemoveAlojamientoTursitico setOauthToken(java.lang.String oauthToken) {
        return (RemoveAlojamientoTursitico) super.setOauthToken(oauthToken);
      }

      @Override
      public RemoveAlojamientoTursitico setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (RemoveAlojamientoTursitico) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public RemoveAlojamientoTursitico setQuotaUser(java.lang.String quotaUser) {
        return (RemoveAlojamientoTursitico) super.setQuotaUser(quotaUser);
      }

      @Override
      public RemoveAlojamientoTursitico setUserIp(java.lang.String userIp) {
        return (RemoveAlojamientoTursitico) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public RemoveAlojamientoTursitico setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public RemoveAlojamientoTursitico set(String parameterName, Object value) {
        return (RemoveAlojamientoTursitico) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "alojamientoTursiticoEndpoint.updateAlojamientoTursitico".
     *
     * This request holds the parameters needed by the the alojamientostursiticos server.  After setting
     * any optional parameters, call the {@link UpdateAlojamientoTursitico#execute()} method to invoke
     * the remote operation.
     *
     * @param content the {@link com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico}
     * @return the request
     */
    public UpdateAlojamientoTursitico updateAlojamientoTursitico(com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico content) throws java.io.IOException {
      UpdateAlojamientoTursitico result = new UpdateAlojamientoTursitico(content);
      initialize(result);
      return result;
    }

    public class UpdateAlojamientoTursitico extends AlojamientostursiticosRequest<com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico> {

      private static final String REST_PATH = "alojamientotursitico";

      /**
       * Create a request for the method "alojamientoTursiticoEndpoint.updateAlojamientoTursitico".
       *
       * This request holds the parameters needed by the the alojamientostursiticos server.  After
       * setting any optional parameters, call the {@link UpdateAlojamientoTursitico#execute()} method
       * to invoke the remote operation. <p> {@link UpdateAlojamientoTursitico#initialize(com.google.api
       * .client.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this
       * instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico}
       * @since 1.13
       */
      protected UpdateAlojamientoTursitico(com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico content) {
        super(Alojamientostursiticos.this, "PUT", REST_PATH, content, com.appspot.ba_info.alojamientostursiticos.model.AlojamientoTursitico.class);
      }

      @Override
      public UpdateAlojamientoTursitico setAlt(java.lang.String alt) {
        return (UpdateAlojamientoTursitico) super.setAlt(alt);
      }

      @Override
      public UpdateAlojamientoTursitico setFields(java.lang.String fields) {
        return (UpdateAlojamientoTursitico) super.setFields(fields);
      }

      @Override
      public UpdateAlojamientoTursitico setKey(java.lang.String key) {
        return (UpdateAlojamientoTursitico) super.setKey(key);
      }

      @Override
      public UpdateAlojamientoTursitico setOauthToken(java.lang.String oauthToken) {
        return (UpdateAlojamientoTursitico) super.setOauthToken(oauthToken);
      }

      @Override
      public UpdateAlojamientoTursitico setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (UpdateAlojamientoTursitico) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public UpdateAlojamientoTursitico setQuotaUser(java.lang.String quotaUser) {
        return (UpdateAlojamientoTursitico) super.setQuotaUser(quotaUser);
      }

      @Override
      public UpdateAlojamientoTursitico setUserIp(java.lang.String userIp) {
        return (UpdateAlojamientoTursitico) super.setUserIp(userIp);
      }

      @Override
      public UpdateAlojamientoTursitico set(String parameterName, Object value) {
        return (UpdateAlojamientoTursitico) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Alojamientostursiticos}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Alojamientostursiticos}. */
    @Override
    public Alojamientostursiticos build() {
      return new Alojamientostursiticos(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AlojamientostursiticosRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAlojamientostursiticosRequestInitializer(
        AlojamientostursiticosRequestInitializer alojamientostursiticosRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(alojamientostursiticosRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
