/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-01 at 01:14:52 UTC 
 * Modify at your own risk.
 */

package com.appspot.ba_info.centroscesac;

/**
 * Service definition for Centroscesac (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link CentroscesacRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Centroscesac extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the centroscesac library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://ba-info.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "centroscesac/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Centroscesac(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Centroscesac(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the CentroAtencionCESACEndpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Centroscesac centroscesac = new Centroscesac(...);}
   *   {@code Centroscesac.CentroAtencionCESACEndpoint.List request = centroscesac.centroAtencionCESACEndpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public CentroAtencionCESACEndpoint centroAtencionCESACEndpoint() {
    return new CentroAtencionCESACEndpoint();
  }

  /**
   * The "centroAtencionCESACEndpoint" collection of methods.
   */
  public class CentroAtencionCESACEndpoint {

    /**
     * Create a request for the method "centroAtencionCESACEndpoint.getCentroAtencionCESAC".
     *
     * This request holds the parameters needed by the the centroscesac server.  After setting any
     * optional parameters, call the {@link GetCentroAtencionCESAC#execute()} method to invoke the
     * remote operation.
     *
     * @param id
     * @return the request
     */
    public GetCentroAtencionCESAC getCentroAtencionCESAC(java.lang.Long id) throws java.io.IOException {
      GetCentroAtencionCESAC result = new GetCentroAtencionCESAC(id);
      initialize(result);
      return result;
    }

    public class GetCentroAtencionCESAC extends CentroscesacRequest<com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC> {

      private static final String REST_PATH = "centroatencioncesac/{id}";

      /**
       * Create a request for the method "centroAtencionCESACEndpoint.getCentroAtencionCESAC".
       *
       * This request holds the parameters needed by the the centroscesac server.  After setting any
       * optional parameters, call the {@link GetCentroAtencionCESAC#execute()} method to invoke the
       * remote operation. <p> {@link GetCentroAtencionCESAC#initialize(com.google.api.client.googleapis
       * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
       * after invoking the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected GetCentroAtencionCESAC(java.lang.Long id) {
        super(Centroscesac.this, "GET", REST_PATH, null, com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetCentroAtencionCESAC setAlt(java.lang.String alt) {
        return (GetCentroAtencionCESAC) super.setAlt(alt);
      }

      @Override
      public GetCentroAtencionCESAC setFields(java.lang.String fields) {
        return (GetCentroAtencionCESAC) super.setFields(fields);
      }

      @Override
      public GetCentroAtencionCESAC setKey(java.lang.String key) {
        return (GetCentroAtencionCESAC) super.setKey(key);
      }

      @Override
      public GetCentroAtencionCESAC setOauthToken(java.lang.String oauthToken) {
        return (GetCentroAtencionCESAC) super.setOauthToken(oauthToken);
      }

      @Override
      public GetCentroAtencionCESAC setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetCentroAtencionCESAC) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetCentroAtencionCESAC setQuotaUser(java.lang.String quotaUser) {
        return (GetCentroAtencionCESAC) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetCentroAtencionCESAC setUserIp(java.lang.String userIp) {
        return (GetCentroAtencionCESAC) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public GetCentroAtencionCESAC setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public GetCentroAtencionCESAC set(String parameterName, Object value) {
        return (GetCentroAtencionCESAC) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "centroAtencionCESACEndpoint.insertCentroAtencionCESAC".
     *
     * This request holds the parameters needed by the the centroscesac server.  After setting any
     * optional parameters, call the {@link InsertCentroAtencionCESAC#execute()} method to invoke the
     * remote operation.
     *
     * @param content the {@link com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC}
     * @return the request
     */
    public InsertCentroAtencionCESAC insertCentroAtencionCESAC(com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC content) throws java.io.IOException {
      InsertCentroAtencionCESAC result = new InsertCentroAtencionCESAC(content);
      initialize(result);
      return result;
    }

    public class InsertCentroAtencionCESAC extends CentroscesacRequest<com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC> {

      private static final String REST_PATH = "centroatencioncesac";

      /**
       * Create a request for the method "centroAtencionCESACEndpoint.insertCentroAtencionCESAC".
       *
       * This request holds the parameters needed by the the centroscesac server.  After setting any
       * optional parameters, call the {@link InsertCentroAtencionCESAC#execute()} method to invoke the
       * remote operation. <p> {@link InsertCentroAtencionCESAC#initialize(com.google.api.client.googlea
       * pis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
       * immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC}
       * @since 1.13
       */
      protected InsertCentroAtencionCESAC(com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC content) {
        super(Centroscesac.this, "POST", REST_PATH, content, com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC.class);
      }

      @Override
      public InsertCentroAtencionCESAC setAlt(java.lang.String alt) {
        return (InsertCentroAtencionCESAC) super.setAlt(alt);
      }

      @Override
      public InsertCentroAtencionCESAC setFields(java.lang.String fields) {
        return (InsertCentroAtencionCESAC) super.setFields(fields);
      }

      @Override
      public InsertCentroAtencionCESAC setKey(java.lang.String key) {
        return (InsertCentroAtencionCESAC) super.setKey(key);
      }

      @Override
      public InsertCentroAtencionCESAC setOauthToken(java.lang.String oauthToken) {
        return (InsertCentroAtencionCESAC) super.setOauthToken(oauthToken);
      }

      @Override
      public InsertCentroAtencionCESAC setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (InsertCentroAtencionCESAC) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public InsertCentroAtencionCESAC setQuotaUser(java.lang.String quotaUser) {
        return (InsertCentroAtencionCESAC) super.setQuotaUser(quotaUser);
      }

      @Override
      public InsertCentroAtencionCESAC setUserIp(java.lang.String userIp) {
        return (InsertCentroAtencionCESAC) super.setUserIp(userIp);
      }

      @Override
      public InsertCentroAtencionCESAC set(String parameterName, Object value) {
        return (InsertCentroAtencionCESAC) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "centroAtencionCESACEndpoint.listCentroAtencionCESAC".
     *
     * This request holds the parameters needed by the the centroscesac server.  After setting any
     * optional parameters, call the {@link ListCentroAtencionCESAC#execute()} method to invoke the
     * remote operation.
     *
     * @return the request
     */
    public ListCentroAtencionCESAC listCentroAtencionCESAC() throws java.io.IOException {
      ListCentroAtencionCESAC result = new ListCentroAtencionCESAC();
      initialize(result);
      return result;
    }

    public class ListCentroAtencionCESAC extends CentroscesacRequest<com.appspot.ba_info.centroscesac.model.CentroAtencionCESACCollection> {

      private static final String REST_PATH = "centroatencioncesac";

      /**
       * Create a request for the method "centroAtencionCESACEndpoint.listCentroAtencionCESAC".
       *
       * This request holds the parameters needed by the the centroscesac server.  After setting any
       * optional parameters, call the {@link ListCentroAtencionCESAC#execute()} method to invoke the
       * remote operation. <p> {@link ListCentroAtencionCESAC#initialize(com.google.api.client.googleapi
       * s.services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
       * after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected ListCentroAtencionCESAC() {
        super(Centroscesac.this, "GET", REST_PATH, null, com.appspot.ba_info.centroscesac.model.CentroAtencionCESACCollection.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public ListCentroAtencionCESAC setAlt(java.lang.String alt) {
        return (ListCentroAtencionCESAC) super.setAlt(alt);
      }

      @Override
      public ListCentroAtencionCESAC setFields(java.lang.String fields) {
        return (ListCentroAtencionCESAC) super.setFields(fields);
      }

      @Override
      public ListCentroAtencionCESAC setKey(java.lang.String key) {
        return (ListCentroAtencionCESAC) super.setKey(key);
      }

      @Override
      public ListCentroAtencionCESAC setOauthToken(java.lang.String oauthToken) {
        return (ListCentroAtencionCESAC) super.setOauthToken(oauthToken);
      }

      @Override
      public ListCentroAtencionCESAC setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (ListCentroAtencionCESAC) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public ListCentroAtencionCESAC setQuotaUser(java.lang.String quotaUser) {
        return (ListCentroAtencionCESAC) super.setQuotaUser(quotaUser);
      }

      @Override
      public ListCentroAtencionCESAC setUserIp(java.lang.String userIp) {
        return (ListCentroAtencionCESAC) super.setUserIp(userIp);
      }

      @Override
      public ListCentroAtencionCESAC set(String parameterName, Object value) {
        return (ListCentroAtencionCESAC) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "centroAtencionCESACEndpoint.removeCentroAtencionCESAC".
     *
     * This request holds the parameters needed by the the centroscesac server.  After setting any
     * optional parameters, call the {@link RemoveCentroAtencionCESAC#execute()} method to invoke the
     * remote operation.
     *
     * @param id
     * @return the request
     */
    public RemoveCentroAtencionCESAC removeCentroAtencionCESAC(java.lang.Long id) throws java.io.IOException {
      RemoveCentroAtencionCESAC result = new RemoveCentroAtencionCESAC(id);
      initialize(result);
      return result;
    }

    public class RemoveCentroAtencionCESAC extends CentroscesacRequest<com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC> {

      private static final String REST_PATH = "centroatencioncesac/{id}";

      /**
       * Create a request for the method "centroAtencionCESACEndpoint.removeCentroAtencionCESAC".
       *
       * This request holds the parameters needed by the the centroscesac server.  After setting any
       * optional parameters, call the {@link RemoveCentroAtencionCESAC#execute()} method to invoke the
       * remote operation. <p> {@link RemoveCentroAtencionCESAC#initialize(com.google.api.client.googlea
       * pis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
       * immediately after invoking the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected RemoveCentroAtencionCESAC(java.lang.Long id) {
        super(Centroscesac.this, "DELETE", REST_PATH, null, com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public RemoveCentroAtencionCESAC setAlt(java.lang.String alt) {
        return (RemoveCentroAtencionCESAC) super.setAlt(alt);
      }

      @Override
      public RemoveCentroAtencionCESAC setFields(java.lang.String fields) {
        return (RemoveCentroAtencionCESAC) super.setFields(fields);
      }

      @Override
      public RemoveCentroAtencionCESAC setKey(java.lang.String key) {
        return (RemoveCentroAtencionCESAC) super.setKey(key);
      }

      @Override
      public RemoveCentroAtencionCESAC setOauthToken(java.lang.String oauthToken) {
        return (RemoveCentroAtencionCESAC) super.setOauthToken(oauthToken);
      }

      @Override
      public RemoveCentroAtencionCESAC setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (RemoveCentroAtencionCESAC) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public RemoveCentroAtencionCESAC setQuotaUser(java.lang.String quotaUser) {
        return (RemoveCentroAtencionCESAC) super.setQuotaUser(quotaUser);
      }

      @Override
      public RemoveCentroAtencionCESAC setUserIp(java.lang.String userIp) {
        return (RemoveCentroAtencionCESAC) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public RemoveCentroAtencionCESAC setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public RemoveCentroAtencionCESAC set(String parameterName, Object value) {
        return (RemoveCentroAtencionCESAC) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "centroAtencionCESACEndpoint.updateCentroAtencionCESAC".
     *
     * This request holds the parameters needed by the the centroscesac server.  After setting any
     * optional parameters, call the {@link UpdateCentroAtencionCESAC#execute()} method to invoke the
     * remote operation.
     *
     * @param content the {@link com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC}
     * @return the request
     */
    public UpdateCentroAtencionCESAC updateCentroAtencionCESAC(com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC content) throws java.io.IOException {
      UpdateCentroAtencionCESAC result = new UpdateCentroAtencionCESAC(content);
      initialize(result);
      return result;
    }

    public class UpdateCentroAtencionCESAC extends CentroscesacRequest<com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC> {

      private static final String REST_PATH = "centroatencioncesac";

      /**
       * Create a request for the method "centroAtencionCESACEndpoint.updateCentroAtencionCESAC".
       *
       * This request holds the parameters needed by the the centroscesac server.  After setting any
       * optional parameters, call the {@link UpdateCentroAtencionCESAC#execute()} method to invoke the
       * remote operation. <p> {@link UpdateCentroAtencionCESAC#initialize(com.google.api.client.googlea
       * pis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
       * immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC}
       * @since 1.13
       */
      protected UpdateCentroAtencionCESAC(com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC content) {
        super(Centroscesac.this, "PUT", REST_PATH, content, com.appspot.ba_info.centroscesac.model.CentroAtencionCESAC.class);
      }

      @Override
      public UpdateCentroAtencionCESAC setAlt(java.lang.String alt) {
        return (UpdateCentroAtencionCESAC) super.setAlt(alt);
      }

      @Override
      public UpdateCentroAtencionCESAC setFields(java.lang.String fields) {
        return (UpdateCentroAtencionCESAC) super.setFields(fields);
      }

      @Override
      public UpdateCentroAtencionCESAC setKey(java.lang.String key) {
        return (UpdateCentroAtencionCESAC) super.setKey(key);
      }

      @Override
      public UpdateCentroAtencionCESAC setOauthToken(java.lang.String oauthToken) {
        return (UpdateCentroAtencionCESAC) super.setOauthToken(oauthToken);
      }

      @Override
      public UpdateCentroAtencionCESAC setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (UpdateCentroAtencionCESAC) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public UpdateCentroAtencionCESAC setQuotaUser(java.lang.String quotaUser) {
        return (UpdateCentroAtencionCESAC) super.setQuotaUser(quotaUser);
      }

      @Override
      public UpdateCentroAtencionCESAC setUserIp(java.lang.String userIp) {
        return (UpdateCentroAtencionCESAC) super.setUserIp(userIp);
      }

      @Override
      public UpdateCentroAtencionCESAC set(String parameterName, Object value) {
        return (UpdateCentroAtencionCESAC) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Centroscesac}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Centroscesac}. */
    @Override
    public Centroscesac build() {
      return new Centroscesac(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link CentroscesacRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setCentroscesacRequestInitializer(
        CentroscesacRequestInitializer centroscesacRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(centroscesacRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
