/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-01 at 01:16:53 UTC 
 * Modify at your own risk.
 */

package com.appspot.ba_info.agenciasviajes;

/**
 * Service definition for Agenciasviajes (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AgenciasviajesRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Agenciasviajes extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the agenciasviajes library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://ba-info.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "agenciasviajes/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Agenciasviajes(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Agenciasviajes(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the AgenciaViajesEndpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Agenciasviajes agenciasviajes = new Agenciasviajes(...);}
   *   {@code Agenciasviajes.AgenciaViajesEndpoint.List request = agenciasviajes.agenciaViajesEndpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public AgenciaViajesEndpoint agenciaViajesEndpoint() {
    return new AgenciaViajesEndpoint();
  }

  /**
   * The "agenciaViajesEndpoint" collection of methods.
   */
  public class AgenciaViajesEndpoint {

    /**
     * Create a request for the method "agenciaViajesEndpoint.getAgenciaViajes".
     *
     * This request holds the parameters needed by the the agenciasviajes server.  After setting any
     * optional parameters, call the {@link GetAgenciaViajes#execute()} method to invoke the remote
     * operation.
     *
     * @param id
     * @return the request
     */
    public GetAgenciaViajes getAgenciaViajes(java.lang.Long id) throws java.io.IOException {
      GetAgenciaViajes result = new GetAgenciaViajes(id);
      initialize(result);
      return result;
    }

    public class GetAgenciaViajes extends AgenciasviajesRequest<com.appspot.ba_info.agenciasviajes.model.AgenciaViajes> {

      private static final String REST_PATH = "agenciaviajes/{id}";

      /**
       * Create a request for the method "agenciaViajesEndpoint.getAgenciaViajes".
       *
       * This request holds the parameters needed by the the agenciasviajes server.  After setting any
       * optional parameters, call the {@link GetAgenciaViajes#execute()} method to invoke the remote
       * operation. <p> {@link GetAgenciaViajes#initialize(com.google.api.client.googleapis.services.Abs
       * tractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected GetAgenciaViajes(java.lang.Long id) {
        super(Agenciasviajes.this, "GET", REST_PATH, null, com.appspot.ba_info.agenciasviajes.model.AgenciaViajes.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetAgenciaViajes setAlt(java.lang.String alt) {
        return (GetAgenciaViajes) super.setAlt(alt);
      }

      @Override
      public GetAgenciaViajes setFields(java.lang.String fields) {
        return (GetAgenciaViajes) super.setFields(fields);
      }

      @Override
      public GetAgenciaViajes setKey(java.lang.String key) {
        return (GetAgenciaViajes) super.setKey(key);
      }

      @Override
      public GetAgenciaViajes setOauthToken(java.lang.String oauthToken) {
        return (GetAgenciaViajes) super.setOauthToken(oauthToken);
      }

      @Override
      public GetAgenciaViajes setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetAgenciaViajes) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetAgenciaViajes setQuotaUser(java.lang.String quotaUser) {
        return (GetAgenciaViajes) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetAgenciaViajes setUserIp(java.lang.String userIp) {
        return (GetAgenciaViajes) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public GetAgenciaViajes setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public GetAgenciaViajes set(String parameterName, Object value) {
        return (GetAgenciaViajes) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "agenciaViajesEndpoint.insertAgenciaViajes".
     *
     * This request holds the parameters needed by the the agenciasviajes server.  After setting any
     * optional parameters, call the {@link InsertAgenciaViajes#execute()} method to invoke the remote
     * operation.
     *
     * @param content the {@link com.appspot.ba_info.agenciasviajes.model.AgenciaViajes}
     * @return the request
     */
    public InsertAgenciaViajes insertAgenciaViajes(com.appspot.ba_info.agenciasviajes.model.AgenciaViajes content) throws java.io.IOException {
      InsertAgenciaViajes result = new InsertAgenciaViajes(content);
      initialize(result);
      return result;
    }

    public class InsertAgenciaViajes extends AgenciasviajesRequest<com.appspot.ba_info.agenciasviajes.model.AgenciaViajes> {

      private static final String REST_PATH = "agenciaviajes";

      /**
       * Create a request for the method "agenciaViajesEndpoint.insertAgenciaViajes".
       *
       * This request holds the parameters needed by the the agenciasviajes server.  After setting any
       * optional parameters, call the {@link InsertAgenciaViajes#execute()} method to invoke the remote
       * operation. <p> {@link InsertAgenciaViajes#initialize(com.google.api.client.googleapis.services.
       * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.ba_info.agenciasviajes.model.AgenciaViajes}
       * @since 1.13
       */
      protected InsertAgenciaViajes(com.appspot.ba_info.agenciasviajes.model.AgenciaViajes content) {
        super(Agenciasviajes.this, "POST", REST_PATH, content, com.appspot.ba_info.agenciasviajes.model.AgenciaViajes.class);
      }

      @Override
      public InsertAgenciaViajes setAlt(java.lang.String alt) {
        return (InsertAgenciaViajes) super.setAlt(alt);
      }

      @Override
      public InsertAgenciaViajes setFields(java.lang.String fields) {
        return (InsertAgenciaViajes) super.setFields(fields);
      }

      @Override
      public InsertAgenciaViajes setKey(java.lang.String key) {
        return (InsertAgenciaViajes) super.setKey(key);
      }

      @Override
      public InsertAgenciaViajes setOauthToken(java.lang.String oauthToken) {
        return (InsertAgenciaViajes) super.setOauthToken(oauthToken);
      }

      @Override
      public InsertAgenciaViajes setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (InsertAgenciaViajes) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public InsertAgenciaViajes setQuotaUser(java.lang.String quotaUser) {
        return (InsertAgenciaViajes) super.setQuotaUser(quotaUser);
      }

      @Override
      public InsertAgenciaViajes setUserIp(java.lang.String userIp) {
        return (InsertAgenciaViajes) super.setUserIp(userIp);
      }

      @Override
      public InsertAgenciaViajes set(String parameterName, Object value) {
        return (InsertAgenciaViajes) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "agenciaViajesEndpoint.listAgenciaViajes".
     *
     * This request holds the parameters needed by the the agenciasviajes server.  After setting any
     * optional parameters, call the {@link ListAgenciaViajes#execute()} method to invoke the remote
     * operation.
     *
     * @return the request
     */
    public ListAgenciaViajes listAgenciaViajes() throws java.io.IOException {
      ListAgenciaViajes result = new ListAgenciaViajes();
      initialize(result);
      return result;
    }

    public class ListAgenciaViajes extends AgenciasviajesRequest<com.appspot.ba_info.agenciasviajes.model.AgenciaViajesCollection> {

      private static final String REST_PATH = "agenciaviajes";

      /**
       * Create a request for the method "agenciaViajesEndpoint.listAgenciaViajes".
       *
       * This request holds the parameters needed by the the agenciasviajes server.  After setting any
       * optional parameters, call the {@link ListAgenciaViajes#execute()} method to invoke the remote
       * operation. <p> {@link ListAgenciaViajes#initialize(com.google.api.client.googleapis.services.Ab
       * stractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected ListAgenciaViajes() {
        super(Agenciasviajes.this, "GET", REST_PATH, null, com.appspot.ba_info.agenciasviajes.model.AgenciaViajesCollection.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public ListAgenciaViajes setAlt(java.lang.String alt) {
        return (ListAgenciaViajes) super.setAlt(alt);
      }

      @Override
      public ListAgenciaViajes setFields(java.lang.String fields) {
        return (ListAgenciaViajes) super.setFields(fields);
      }

      @Override
      public ListAgenciaViajes setKey(java.lang.String key) {
        return (ListAgenciaViajes) super.setKey(key);
      }

      @Override
      public ListAgenciaViajes setOauthToken(java.lang.String oauthToken) {
        return (ListAgenciaViajes) super.setOauthToken(oauthToken);
      }

      @Override
      public ListAgenciaViajes setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (ListAgenciaViajes) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public ListAgenciaViajes setQuotaUser(java.lang.String quotaUser) {
        return (ListAgenciaViajes) super.setQuotaUser(quotaUser);
      }

      @Override
      public ListAgenciaViajes setUserIp(java.lang.String userIp) {
        return (ListAgenciaViajes) super.setUserIp(userIp);
      }

      @Override
      public ListAgenciaViajes set(String parameterName, Object value) {
        return (ListAgenciaViajes) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "agenciaViajesEndpoint.removeAgenciaViajes".
     *
     * This request holds the parameters needed by the the agenciasviajes server.  After setting any
     * optional parameters, call the {@link RemoveAgenciaViajes#execute()} method to invoke the remote
     * operation.
     *
     * @param id
     * @return the request
     */
    public RemoveAgenciaViajes removeAgenciaViajes(java.lang.Long id) throws java.io.IOException {
      RemoveAgenciaViajes result = new RemoveAgenciaViajes(id);
      initialize(result);
      return result;
    }

    public class RemoveAgenciaViajes extends AgenciasviajesRequest<com.appspot.ba_info.agenciasviajes.model.AgenciaViajes> {

      private static final String REST_PATH = "agenciaviajes/{id}";

      /**
       * Create a request for the method "agenciaViajesEndpoint.removeAgenciaViajes".
       *
       * This request holds the parameters needed by the the agenciasviajes server.  After setting any
       * optional parameters, call the {@link RemoveAgenciaViajes#execute()} method to invoke the remote
       * operation. <p> {@link RemoveAgenciaViajes#initialize(com.google.api.client.googleapis.services.
       * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected RemoveAgenciaViajes(java.lang.Long id) {
        super(Agenciasviajes.this, "DELETE", REST_PATH, null, com.appspot.ba_info.agenciasviajes.model.AgenciaViajes.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public RemoveAgenciaViajes setAlt(java.lang.String alt) {
        return (RemoveAgenciaViajes) super.setAlt(alt);
      }

      @Override
      public RemoveAgenciaViajes setFields(java.lang.String fields) {
        return (RemoveAgenciaViajes) super.setFields(fields);
      }

      @Override
      public RemoveAgenciaViajes setKey(java.lang.String key) {
        return (RemoveAgenciaViajes) super.setKey(key);
      }

      @Override
      public RemoveAgenciaViajes setOauthToken(java.lang.String oauthToken) {
        return (RemoveAgenciaViajes) super.setOauthToken(oauthToken);
      }

      @Override
      public RemoveAgenciaViajes setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (RemoveAgenciaViajes) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public RemoveAgenciaViajes setQuotaUser(java.lang.String quotaUser) {
        return (RemoveAgenciaViajes) super.setQuotaUser(quotaUser);
      }

      @Override
      public RemoveAgenciaViajes setUserIp(java.lang.String userIp) {
        return (RemoveAgenciaViajes) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public RemoveAgenciaViajes setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public RemoveAgenciaViajes set(String parameterName, Object value) {
        return (RemoveAgenciaViajes) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "agenciaViajesEndpoint.updateAgenciaViajes".
     *
     * This request holds the parameters needed by the the agenciasviajes server.  After setting any
     * optional parameters, call the {@link UpdateAgenciaViajes#execute()} method to invoke the remote
     * operation.
     *
     * @param content the {@link com.appspot.ba_info.agenciasviajes.model.AgenciaViajes}
     * @return the request
     */
    public UpdateAgenciaViajes updateAgenciaViajes(com.appspot.ba_info.agenciasviajes.model.AgenciaViajes content) throws java.io.IOException {
      UpdateAgenciaViajes result = new UpdateAgenciaViajes(content);
      initialize(result);
      return result;
    }

    public class UpdateAgenciaViajes extends AgenciasviajesRequest<com.appspot.ba_info.agenciasviajes.model.AgenciaViajes> {

      private static final String REST_PATH = "agenciaviajes";

      /**
       * Create a request for the method "agenciaViajesEndpoint.updateAgenciaViajes".
       *
       * This request holds the parameters needed by the the agenciasviajes server.  After setting any
       * optional parameters, call the {@link UpdateAgenciaViajes#execute()} method to invoke the remote
       * operation. <p> {@link UpdateAgenciaViajes#initialize(com.google.api.client.googleapis.services.
       * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.ba_info.agenciasviajes.model.AgenciaViajes}
       * @since 1.13
       */
      protected UpdateAgenciaViajes(com.appspot.ba_info.agenciasviajes.model.AgenciaViajes content) {
        super(Agenciasviajes.this, "PUT", REST_PATH, content, com.appspot.ba_info.agenciasviajes.model.AgenciaViajes.class);
      }

      @Override
      public UpdateAgenciaViajes setAlt(java.lang.String alt) {
        return (UpdateAgenciaViajes) super.setAlt(alt);
      }

      @Override
      public UpdateAgenciaViajes setFields(java.lang.String fields) {
        return (UpdateAgenciaViajes) super.setFields(fields);
      }

      @Override
      public UpdateAgenciaViajes setKey(java.lang.String key) {
        return (UpdateAgenciaViajes) super.setKey(key);
      }

      @Override
      public UpdateAgenciaViajes setOauthToken(java.lang.String oauthToken) {
        return (UpdateAgenciaViajes) super.setOauthToken(oauthToken);
      }

      @Override
      public UpdateAgenciaViajes setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (UpdateAgenciaViajes) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public UpdateAgenciaViajes setQuotaUser(java.lang.String quotaUser) {
        return (UpdateAgenciaViajes) super.setQuotaUser(quotaUser);
      }

      @Override
      public UpdateAgenciaViajes setUserIp(java.lang.String userIp) {
        return (UpdateAgenciaViajes) super.setUserIp(userIp);
      }

      @Override
      public UpdateAgenciaViajes set(String parameterName, Object value) {
        return (UpdateAgenciaViajes) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Agenciasviajes}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Agenciasviajes}. */
    @Override
    public Agenciasviajes build() {
      return new Agenciasviajes(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AgenciasviajesRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAgenciasviajesRequestInitializer(
        AgenciasviajesRequestInitializer agenciasviajesRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(agenciasviajesRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
