/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-01 at 01:17:57 UTC 
 * Modify at your own risk.
 */

package com.appspot.ba_info.alojamientostursiticos.model;

/**
 * Model definition for AlojamientoTursitico.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the alojamientostursiticos. For a detailed explanation
 * see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AlojamientoTursitico extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String altura;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String categoria;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String direccion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String domicilio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float latitud;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float longitud;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombre;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String separatorChar;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sourceURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String telefono;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ubicacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String web;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAltura() {
    return altura;
  }

  /**
   * @param altura altura or {@code null} for none
   */
  public AlojamientoTursitico setAltura(java.lang.String altura) {
    this.altura = altura;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCategoria() {
    return categoria;
  }

  /**
   * @param categoria categoria or {@code null} for none
   */
  public AlojamientoTursitico setCategoria(java.lang.String categoria) {
    this.categoria = categoria;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDireccion() {
    return direccion;
  }

  /**
   * @param direccion direccion or {@code null} for none
   */
  public AlojamientoTursitico setDireccion(java.lang.String direccion) {
    this.direccion = direccion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDomicilio() {
    return domicilio;
  }

  /**
   * @param domicilio domicilio or {@code null} for none
   */
  public AlojamientoTursitico setDomicilio(java.lang.String domicilio) {
    this.domicilio = domicilio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public AlojamientoTursitico setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public AlojamientoTursitico setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getLatitud() {
    return latitud;
  }

  /**
   * @param latitud latitud or {@code null} for none
   */
  public AlojamientoTursitico setLatitud(java.lang.Float latitud) {
    this.latitud = latitud;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getLongitud() {
    return longitud;
  }

  /**
   * @param longitud longitud or {@code null} for none
   */
  public AlojamientoTursitico setLongitud(java.lang.Float longitud) {
    this.longitud = longitud;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombre() {
    return nombre;
  }

  /**
   * @param nombre nombre or {@code null} for none
   */
  public AlojamientoTursitico setNombre(java.lang.String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSeparatorChar() {
    return separatorChar;
  }

  /**
   * @param separatorChar separatorChar or {@code null} for none
   */
  public AlojamientoTursitico setSeparatorChar(java.lang.String separatorChar) {
    this.separatorChar = separatorChar;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSourceURL() {
    return sourceURL;
  }

  /**
   * @param sourceURL sourceURL or {@code null} for none
   */
  public AlojamientoTursitico setSourceURL(java.lang.String sourceURL) {
    this.sourceURL = sourceURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTelefono() {
    return telefono;
  }

  /**
   * @param telefono telefono or {@code null} for none
   */
  public AlojamientoTursitico setTelefono(java.lang.String telefono) {
    this.telefono = telefono;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUbicacion() {
    return ubicacion;
  }

  /**
   * @param ubicacion ubicacion or {@code null} for none
   */
  public AlojamientoTursitico setUbicacion(java.lang.String ubicacion) {
    this.ubicacion = ubicacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWeb() {
    return web;
  }

  /**
   * @param web web or {@code null} for none
   */
  public AlojamientoTursitico setWeb(java.lang.String web) {
    this.web = web;
    return this;
  }

  @Override
  public AlojamientoTursitico set(String fieldName, Object value) {
    return (AlojamientoTursitico) super.set(fieldName, value);
  }

  @Override
  public AlojamientoTursitico clone() {
    return (AlojamientoTursitico) super.clone();
  }

}
