/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-01 at 01:16:12 UTC 
 * Modify at your own risk.
 */

package com.appspot.ba_info.comisarias;

/**
 * Service definition for Comisarias (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ComisariasRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Comisarias extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the comisarias library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://ba-info.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "comisarias/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Comisarias(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Comisarias(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the ComisariaEndpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Comisarias comisarias = new Comisarias(...);}
   *   {@code Comisarias.ComisariaEndpoint.List request = comisarias.comisariaEndpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public ComisariaEndpoint comisariaEndpoint() {
    return new ComisariaEndpoint();
  }

  /**
   * The "comisariaEndpoint" collection of methods.
   */
  public class ComisariaEndpoint {

    /**
     * Create a request for the method "comisariaEndpoint.getComisaria".
     *
     * This request holds the parameters needed by the the comisarias server.  After setting any
     * optional parameters, call the {@link GetComisaria#execute()} method to invoke the remote
     * operation.
     *
     * @param id
     * @return the request
     */
    public GetComisaria getComisaria(java.lang.Long id) throws java.io.IOException {
      GetComisaria result = new GetComisaria(id);
      initialize(result);
      return result;
    }

    public class GetComisaria extends ComisariasRequest<com.appspot.ba_info.comisarias.model.Comisaria> {

      private static final String REST_PATH = "comisaria/{id}";

      /**
       * Create a request for the method "comisariaEndpoint.getComisaria".
       *
       * This request holds the parameters needed by the the comisarias server.  After setting any
       * optional parameters, call the {@link GetComisaria#execute()} method to invoke the remote
       * operation. <p> {@link
       * GetComisaria#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected GetComisaria(java.lang.Long id) {
        super(Comisarias.this, "GET", REST_PATH, null, com.appspot.ba_info.comisarias.model.Comisaria.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetComisaria setAlt(java.lang.String alt) {
        return (GetComisaria) super.setAlt(alt);
      }

      @Override
      public GetComisaria setFields(java.lang.String fields) {
        return (GetComisaria) super.setFields(fields);
      }

      @Override
      public GetComisaria setKey(java.lang.String key) {
        return (GetComisaria) super.setKey(key);
      }

      @Override
      public GetComisaria setOauthToken(java.lang.String oauthToken) {
        return (GetComisaria) super.setOauthToken(oauthToken);
      }

      @Override
      public GetComisaria setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetComisaria) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetComisaria setQuotaUser(java.lang.String quotaUser) {
        return (GetComisaria) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetComisaria setUserIp(java.lang.String userIp) {
        return (GetComisaria) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public GetComisaria setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public GetComisaria set(String parameterName, Object value) {
        return (GetComisaria) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "comisariaEndpoint.insertComisaria".
     *
     * This request holds the parameters needed by the the comisarias server.  After setting any
     * optional parameters, call the {@link InsertComisaria#execute()} method to invoke the remote
     * operation.
     *
     * @param content the {@link com.appspot.ba_info.comisarias.model.Comisaria}
     * @return the request
     */
    public InsertComisaria insertComisaria(com.appspot.ba_info.comisarias.model.Comisaria content) throws java.io.IOException {
      InsertComisaria result = new InsertComisaria(content);
      initialize(result);
      return result;
    }

    public class InsertComisaria extends ComisariasRequest<com.appspot.ba_info.comisarias.model.Comisaria> {

      private static final String REST_PATH = "comisaria";

      /**
       * Create a request for the method "comisariaEndpoint.insertComisaria".
       *
       * This request holds the parameters needed by the the comisarias server.  After setting any
       * optional parameters, call the {@link InsertComisaria#execute()} method to invoke the remote
       * operation. <p> {@link InsertComisaria#initialize(com.google.api.client.googleapis.services.Abst
       * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param content the {@link com.appspot.ba_info.comisarias.model.Comisaria}
       * @since 1.13
       */
      protected InsertComisaria(com.appspot.ba_info.comisarias.model.Comisaria content) {
        super(Comisarias.this, "POST", REST_PATH, content, com.appspot.ba_info.comisarias.model.Comisaria.class);
      }

      @Override
      public InsertComisaria setAlt(java.lang.String alt) {
        return (InsertComisaria) super.setAlt(alt);
      }

      @Override
      public InsertComisaria setFields(java.lang.String fields) {
        return (InsertComisaria) super.setFields(fields);
      }

      @Override
      public InsertComisaria setKey(java.lang.String key) {
        return (InsertComisaria) super.setKey(key);
      }

      @Override
      public InsertComisaria setOauthToken(java.lang.String oauthToken) {
        return (InsertComisaria) super.setOauthToken(oauthToken);
      }

      @Override
      public InsertComisaria setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (InsertComisaria) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public InsertComisaria setQuotaUser(java.lang.String quotaUser) {
        return (InsertComisaria) super.setQuotaUser(quotaUser);
      }

      @Override
      public InsertComisaria setUserIp(java.lang.String userIp) {
        return (InsertComisaria) super.setUserIp(userIp);
      }

      @Override
      public InsertComisaria set(String parameterName, Object value) {
        return (InsertComisaria) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "comisariaEndpoint.listComisaria".
     *
     * This request holds the parameters needed by the the comisarias server.  After setting any
     * optional parameters, call the {@link ListComisaria#execute()} method to invoke the remote
     * operation.
     *
     * @return the request
     */
    public ListComisaria listComisaria() throws java.io.IOException {
      ListComisaria result = new ListComisaria();
      initialize(result);
      return result;
    }

    public class ListComisaria extends ComisariasRequest<com.appspot.ba_info.comisarias.model.ComisariaCollection> {

      private static final String REST_PATH = "comisaria";

      /**
       * Create a request for the method "comisariaEndpoint.listComisaria".
       *
       * This request holds the parameters needed by the the comisarias server.  After setting any
       * optional parameters, call the {@link ListComisaria#execute()} method to invoke the remote
       * operation. <p> {@link ListComisaria#initialize(com.google.api.client.googleapis.services.Abstra
       * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @since 1.13
       */
      protected ListComisaria() {
        super(Comisarias.this, "GET", REST_PATH, null, com.appspot.ba_info.comisarias.model.ComisariaCollection.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public ListComisaria setAlt(java.lang.String alt) {
        return (ListComisaria) super.setAlt(alt);
      }

      @Override
      public ListComisaria setFields(java.lang.String fields) {
        return (ListComisaria) super.setFields(fields);
      }

      @Override
      public ListComisaria setKey(java.lang.String key) {
        return (ListComisaria) super.setKey(key);
      }

      @Override
      public ListComisaria setOauthToken(java.lang.String oauthToken) {
        return (ListComisaria) super.setOauthToken(oauthToken);
      }

      @Override
      public ListComisaria setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (ListComisaria) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public ListComisaria setQuotaUser(java.lang.String quotaUser) {
        return (ListComisaria) super.setQuotaUser(quotaUser);
      }

      @Override
      public ListComisaria setUserIp(java.lang.String userIp) {
        return (ListComisaria) super.setUserIp(userIp);
      }

      @Override
      public ListComisaria set(String parameterName, Object value) {
        return (ListComisaria) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "comisariaEndpoint.removeComisaria".
     *
     * This request holds the parameters needed by the the comisarias server.  After setting any
     * optional parameters, call the {@link RemoveComisaria#execute()} method to invoke the remote
     * operation.
     *
     * @param id
     * @return the request
     */
    public RemoveComisaria removeComisaria(java.lang.Long id) throws java.io.IOException {
      RemoveComisaria result = new RemoveComisaria(id);
      initialize(result);
      return result;
    }

    public class RemoveComisaria extends ComisariasRequest<com.appspot.ba_info.comisarias.model.Comisaria> {

      private static final String REST_PATH = "comisaria/{id}";

      /**
       * Create a request for the method "comisariaEndpoint.removeComisaria".
       *
       * This request holds the parameters needed by the the comisarias server.  After setting any
       * optional parameters, call the {@link RemoveComisaria#execute()} method to invoke the remote
       * operation. <p> {@link RemoveComisaria#initialize(com.google.api.client.googleapis.services.Abst
       * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected RemoveComisaria(java.lang.Long id) {
        super(Comisarias.this, "DELETE", REST_PATH, null, com.appspot.ba_info.comisarias.model.Comisaria.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public RemoveComisaria setAlt(java.lang.String alt) {
        return (RemoveComisaria) super.setAlt(alt);
      }

      @Override
      public RemoveComisaria setFields(java.lang.String fields) {
        return (RemoveComisaria) super.setFields(fields);
      }

      @Override
      public RemoveComisaria setKey(java.lang.String key) {
        return (RemoveComisaria) super.setKey(key);
      }

      @Override
      public RemoveComisaria setOauthToken(java.lang.String oauthToken) {
        return (RemoveComisaria) super.setOauthToken(oauthToken);
      }

      @Override
      public RemoveComisaria setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (RemoveComisaria) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public RemoveComisaria setQuotaUser(java.lang.String quotaUser) {
        return (RemoveComisaria) super.setQuotaUser(quotaUser);
      }

      @Override
      public RemoveComisaria setUserIp(java.lang.String userIp) {
        return (RemoveComisaria) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public RemoveComisaria setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public RemoveComisaria set(String parameterName, Object value) {
        return (RemoveComisaria) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "comisariaEndpoint.updateComisaria".
     *
     * This request holds the parameters needed by the the comisarias server.  After setting any
     * optional parameters, call the {@link UpdateComisaria#execute()} method to invoke the remote
     * operation.
     *
     * @param content the {@link com.appspot.ba_info.comisarias.model.Comisaria}
     * @return the request
     */
    public UpdateComisaria updateComisaria(com.appspot.ba_info.comisarias.model.Comisaria content) throws java.io.IOException {
      UpdateComisaria result = new UpdateComisaria(content);
      initialize(result);
      return result;
    }

    public class UpdateComisaria extends ComisariasRequest<com.appspot.ba_info.comisarias.model.Comisaria> {

      private static final String REST_PATH = "comisaria";

      /**
       * Create a request for the method "comisariaEndpoint.updateComisaria".
       *
       * This request holds the parameters needed by the the comisarias server.  After setting any
       * optional parameters, call the {@link UpdateComisaria#execute()} method to invoke the remote
       * operation. <p> {@link UpdateComisaria#initialize(com.google.api.client.googleapis.services.Abst
       * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param content the {@link com.appspot.ba_info.comisarias.model.Comisaria}
       * @since 1.13
       */
      protected UpdateComisaria(com.appspot.ba_info.comisarias.model.Comisaria content) {
        super(Comisarias.this, "PUT", REST_PATH, content, com.appspot.ba_info.comisarias.model.Comisaria.class);
      }

      @Override
      public UpdateComisaria setAlt(java.lang.String alt) {
        return (UpdateComisaria) super.setAlt(alt);
      }

      @Override
      public UpdateComisaria setFields(java.lang.String fields) {
        return (UpdateComisaria) super.setFields(fields);
      }

      @Override
      public UpdateComisaria setKey(java.lang.String key) {
        return (UpdateComisaria) super.setKey(key);
      }

      @Override
      public UpdateComisaria setOauthToken(java.lang.String oauthToken) {
        return (UpdateComisaria) super.setOauthToken(oauthToken);
      }

      @Override
      public UpdateComisaria setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (UpdateComisaria) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public UpdateComisaria setQuotaUser(java.lang.String quotaUser) {
        return (UpdateComisaria) super.setQuotaUser(quotaUser);
      }

      @Override
      public UpdateComisaria setUserIp(java.lang.String userIp) {
        return (UpdateComisaria) super.setUserIp(userIp);
      }

      @Override
      public UpdateComisaria set(String parameterName, Object value) {
        return (UpdateComisaria) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Comisarias}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Comisarias}. */
    @Override
    public Comisarias build() {
      return new Comisarias(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ComisariasRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setComisariasRequestInitializer(
        ComisariasRequestInitializer comisariasRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(comisariasRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
